#!/usr/bin/env python3
# [Gedit Tool]
# Name=flexiwrap
# Input=selection
# Output=replace-selection
# Applicability=all
# Save-files=nothing
# Shortcut=<Shift><Alt>w
# Languages=plain,python,python3


import sys
import subprocess as sp

selection = sys.stdin.read()

if selection.strip()[0] == '#':
    cmd = ['fmt', '-w', '80', '-p', '#']
else:
    cmd = ['fmt', '-w', '80']

sp.run(cmd, input=selection, encoding='ascii')
